FROM nginx:latest

COPY ./*.png /usr/share/nginx/html/
COPY ./*.jpg /usr/share/nginx/html/
COPY ./*.html /usr/share/nginx/html/
COPY ./*.js /usr/share/nginx/html/
COPY ./*.css /usr/share/nginx/html/
COPY ./fonts /usr/share/nginx/html/fonts/

WORKDIR /usr/share/nginx/html